export const ECS_FIELD_CATEGORIES = {
  BASE: 'base',
  AGENT: 'agent',
  CLIENT: 'client',
  CLOUD: 'cloud',
  CONTAINER: 'container',
  DESTINATION: 'destination',
  DNS: 'dns',
  ERROR: 'error',
  EVENT: 'event',
  FILE: 'file',
  GEO: 'geo',
  GROUP: 'group',
  HOST: 'host',
  HTTP: 'http',
  LOG: 'log',
  NETWORK: 'network',
  OBSERVER: 'observer',
  ORCHESTRATOR: 'orchestrator',
  ORGANIZATION: 'organization',
  PACKAGE: 'package',
  PROCESS: 'process',
  REGISTRY: 'registry',
  RELATED: 'related',
  RULE: 'rule',
  SERVER: 'server',
  SERVICE: 'service',
  SOURCE: 'source',
  THREAT: 'threat',
  TLS: 'tls',
  TRACE: 'trace',
  URL: 'url',
  USER: 'user',
  USER_AGENT: 'user_agent',
  VULNERABILITY: 'vulnerability',
} as const;

export type ECSFieldCategory =
  (typeof ECS_FIELD_CATEGORIES)[keyof typeof ECS_FIELD_CATEGORIES];

export const ECS_FIELD_TYPES = {
  KEYWORD: 'keyword',
  TEXT: 'text',
  LONG: 'long',
  INTEGER: 'integer',
  FLOAT: 'float',
  DOUBLE: 'double',
  BOOLEAN: 'boolean',
  DATE: 'date',
  IP: 'ip',
  OBJECT: 'object',
  NESTED: 'nested',
  GEO_POINT: 'geo_point',
  WILDCARD: 'wildcard',
  FLATTENED: 'flattened',
} as const;

export type ECSFieldType = (typeof ECS_FIELD_TYPES)[keyof typeof ECS_FIELD_TYPES];

/**
 * High-signal ECS fields frequently used in security investigations.
 * Grouped by investigation relevance to support query construction hints.
 */
export const ECS_SECURITY_FIELDS = {
  PROCESS: [
    'process.name',
    'process.pid',
    'process.ppid',
    'process.args',
    'process.executable',
    'process.command_line',
    'process.parent.name',
    'process.parent.pid',
    'process.parent.executable',
    'process.hash.sha256',
    'process.hash.md5',
  ],
  NETWORK: [
    'network.direction',
    'network.protocol',
    'network.transport',
    'source.ip',
    'source.port',
    'destination.ip',
    'destination.port',
    'dns.question.name',
    'dns.resolved_ip',
    'url.full',
    'url.domain',
  ],
  USER: [
    'user.name',
    'user.id',
    'user.domain',
    'user.effective.name',
    'group.name',
    'group.id',
  ],
  FILE: [
    'file.name',
    'file.path',
    'file.extension',
    'file.hash.sha256',
    'file.hash.md5',
    'file.size',
    'file.created',
    'file.mtime',
  ],
  REGISTRY: [
    'registry.path',
    'registry.key',
    'registry.value.name',
    'registry.value.data.strings',
  ],
  EVENT: [
    'event.action',
    'event.category',
    'event.type',
    'event.outcome',
    'event.severity',
    'event.code',
    'event.id',
  ],
  HOST: [
    'host.name',
    'host.hostname',
    'host.id',
    'host.ip',
    'host.os.name',
    'host.os.version',
    'host.os.type',
  ],
  THREAT: [
    'threat.indicator.ip',
    'threat.indicator.domain',
    'threat.indicator.type',
    'threat.tactic.name',
    'threat.technique.name',
    'threat.technique.id',
  ],
} as const;

export const ECS_INVESTIGATION_TYPE_FIELDS: Record<string, readonly string[]> = {
  brute_force: [
    'event.action',
    'event.outcome',
    'user.name',
    'source.ip',
    'destination.ip',
    '@timestamp',
  ],
  privilege_escalation: [
    'user.name',
    'user.effective.name',
    'process.name',
    'process.args',
    'event.action',
    'host.name',
  ],
  lateral_movement: [
    'source.ip',
    'destination.ip',
    'user.name',
    'event.action',
    'network.protocol',
    'host.name',
  ],
  suspicious_process: [
    'process.name',
    'process.command_line',
    'process.parent.name',
    'process.args',
    'user.name',
    'host.name',
  ],
  persistence: [
    'registry.path',
    'file.path',
    'process.name',
    'event.action',
    'user.name',
    'host.name',
  ],
  unusual_outbound: [
    'destination.ip',
    'destination.port',
    'network.bytes',
    'process.name',
    'source.ip',
    'dns.question.name',
  ],
  suspicious_powershell: [
    'process.name',
    'process.command_line',
    'process.args',
    'process.parent.name',
    'user.name',
    'host.name',
  ],
  auth_anomaly: [
    'user.name',
    'source.ip',
    'event.action',
    'event.outcome',
    'user.domain',
    'host.name',
  ],
  failed_login: [
    'user.name',
    'source.ip',
    'event.outcome',
    'event.action',
    '@timestamp',
    'host.name',
  ],
  parent_child_anomaly: [
    'process.name',
    'process.pid',
    'process.parent.name',
    'process.parent.pid',
    'process.command_line',
    'host.name',
  ],
  threat_hunting: [
    'threat.indicator.ip',
    'threat.technique.id',
    'event.category',
    'host.name',
    'user.name',
    'network.protocol',
  ],
  general: ['event.action', 'event.category', 'host.name', 'user.name', '@timestamp'],
} as const;
