export const ERROR_CODES = {
  // Provider errors
  PROVIDER_UNREACHABLE: 'PROVIDER_UNREACHABLE',
  PROVIDER_AUTH_FAILED: 'PROVIDER_AUTH_FAILED',
  PROVIDER_RATE_LIMITED: 'PROVIDER_RATE_LIMITED',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_INVALID_RESPONSE: 'PROVIDER_INVALID_RESPONSE',
  PROVIDER_CONTEXT_OVERFLOW: 'PROVIDER_CONTEXT_OVERFLOW',
  PROVIDER_NOT_CONFIGURED: 'PROVIDER_NOT_CONFIGURED',
  PROVIDER_MODEL_NOT_FOUND: 'PROVIDER_MODEL_NOT_FOUND',

  // Query pipeline errors
  PIPELINE_QUERY_GENERATION_FAILED: 'PIPELINE_QUERY_GENERATION_FAILED',
  PIPELINE_VALIDATION_FAILED: 'PIPELINE_VALIDATION_FAILED',
  PIPELINE_CORRECTION_FAILED: 'PIPELINE_CORRECTION_FAILED',
  PIPELINE_MAX_CORRECTIONS_EXCEEDED: 'PIPELINE_MAX_CORRECTIONS_EXCEEDED',
  PIPELINE_INTENT_CLASSIFICATION_FAILED: 'PIPELINE_INTENT_CLASSIFICATION_FAILED',
  PIPELINE_CONTEXT_MISSING: 'PIPELINE_CONTEXT_MISSING',
  PIPELINE_ABORTED: 'PIPELINE_ABORTED',

  // Elasticsearch errors
  ES_QUERY_INVALID: 'ES_QUERY_INVALID',
  ES_INDEX_NOT_FOUND: 'ES_INDEX_NOT_FOUND',
  ES_SHARD_FAILURE: 'ES_SHARD_FAILURE',
  ES_TIMEOUT: 'ES_TIMEOUT',
  ES_AUTH_FAILED: 'ES_AUTH_FAILED',
  ES_FIELD_NOT_FOUND: 'ES_FIELD_NOT_FOUND',
  ES_SYNTAX_ERROR: 'ES_SYNTAX_ERROR',

  // Validation errors
  VALIDATION_SCHEMA_MISMATCH: 'VALIDATION_SCHEMA_MISMATCH',
  VALIDATION_REQUIRED_FIELD_MISSING: 'VALIDATION_REQUIRED_FIELD_MISSING',
  VALIDATION_FIELD_TYPE_MISMATCH: 'VALIDATION_FIELD_TYPE_MISMATCH',
  VALIDATION_UNKNOWN_FIELD: 'VALIDATION_UNKNOWN_FIELD',
  VALIDATION_INVALID_AGGREGATION: 'VALIDATION_INVALID_AGGREGATION',
  VALIDATION_RANGE_INVALID: 'VALIDATION_RANGE_INVALID',

  // Cache errors
  CACHE_MISS: 'CACHE_MISS',
  CACHE_WRITE_FAILED: 'CACHE_WRITE_FAILED',
  CACHE_EVICTED: 'CACHE_EVICTED',
  CACHE_CORRUPTED: 'CACHE_CORRUPTED',

  // Intent / NLP errors
  INTENT_AMBIGUOUS: 'INTENT_AMBIGUOUS',
  INTENT_UNSUPPORTED: 'INTENT_UNSUPPORTED',
  INTENT_EMPTY_INPUT: 'INTENT_EMPTY_INPUT',

  // General
  UNKNOWN: 'UNKNOWN',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_SEVERITY = {
  DEBUG: 'debug',
  INFO: 'info',
  WARNING: 'warning',
  ERROR: 'error',
  CRITICAL: 'critical',
} as const;

export type ErrorSeverity = (typeof ERROR_SEVERITY)[keyof typeof ERROR_SEVERITY];

export const ERROR_CATEGORY = {
  PROVIDER: 'provider',
  PIPELINE: 'pipeline',
  ELASTICSEARCH: 'elasticsearch',
  VALIDATION: 'validation',
  CACHE: 'cache',
  INTENT: 'intent',
  SYSTEM: 'system',
} as const;

export type ErrorCategory = (typeof ERROR_CATEGORY)[keyof typeof ERROR_CATEGORY];

export const ERROR_CODE_TO_HTTP_STATUS: Partial<Record<ErrorCode, number>> = {
  PROVIDER_AUTH_FAILED: 401,
  PROVIDER_RATE_LIMITED: 429,
  PROVIDER_TIMEOUT: 504,
  PROVIDER_UNREACHABLE: 503,
  PROVIDER_NOT_CONFIGURED: 422,
  ES_AUTH_FAILED: 401,
  ES_TIMEOUT: 504,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  RATE_LIMIT_EXCEEDED: 429,
  REQUEST_TIMEOUT: 504,
  NOT_IMPLEMENTED: 501,
  INTERNAL_ERROR: 500,
} as const;

export const RETRYABLE_ERROR_CODES = new Set<ErrorCode>([
  ERROR_CODES.PROVIDER_TIMEOUT,
  ERROR_CODES.PROVIDER_RATE_LIMITED,
  ERROR_CODES.ES_TIMEOUT,
  ERROR_CODES.ES_SHARD_FAILURE,
  ERROR_CODES.REQUEST_TIMEOUT,
  ERROR_CODES.CACHE_WRITE_FAILED,
]);
